### PR TITLE
Migrate to official google-breakpad repoes (as submodule)

### PR DESCRIPTION
**Pull request by buzzySmile**
- Setup official google-breakpad repo as git submodule
- Add official google linux-syscall-support  as git submodule
- Improve .gitignore
- Update README.md
- Clean useless files
- Build passed on Linux, OSX and Windows(MinGW)

### CODE REVIEW

**Comment by buzzySmile** [comment]
Hello.
I suggest to start maintain this fork separately from AlekSi original project.
Now it exists as a actual wrapper for up-to-date breakpad official project and AlekSi's project is fully redundant.
Not sure if it's possible to detach fork but maybe you should ask AlekSi to make some kind of link to this repo.

**Comment by pixraider** [comment]
Hello.
I suggest to start maintain this fork separately from AlekSi original project.
Now it exists as a actual wrapper for up-to-date breakpad official project and AlekSi's project is fully redundant.
Not sure if it's possible to detach fork but maybe you should ask AlekSi to make some kind of link to this repo.

**Comment by AlekSi** [comment]
You want me to do something?

**Comment by buzzySmile** [comment]
Still nothing. I'll ask Github support for detach fork with all developing log.
And give you a link to result project.

**Comment by AlekSi** [comment]
> Still nothing.

Let me ask again: you want me to do something and waiting for it?

**Comment by sergey-shambir** [comment]
Maybe you can create organization `breakpad-qt` and transfer repo ownership to this organization? Then add @buzzySmile  and me to this organization, and we will start to maintain repo together =)

**Comment by AlekSi** [comment]
Guys, I moved away from C++ and Qt _years_ ago. It's not for me to decide if any breakpad-qt fork is any good or not. You can continue to maintain this fork, and https://github.com/AlekSi/breakpad-qt will continue to have the current description, linking people to forks. Or you can make a completely separate repository and make sure people do know about it. In that case, the only thing I ask you is to comply to license in `COPYING` file, mentioning me if you use any of my code.

**Comment by buzzySmile** [comment]
Breaking news! 
Yesterday I requested Github support to detach my fork of breakpad-qt and they've done it straight away. It contains all commits upward 'Initial commit' with proper ownerships.

@AlekSi, now you can make mention of [qBreakpad](https://github.com/buzzySmile/qBreakpad) in your description. That's all you need to do.

@sergey-shambir, good idea about organisation. 
But I think it should to be easy-to-integrate project consisting of both client and server side.
I searched breakpad server but haven't found out relevant candidate, stable and easy configured.
To be honest I'm not good in back-end but I entirely sure organisation have to contains this part.

Do you have any thoughts?

**Pull request merged**
